// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEn7z7ApaB39hf9_6fGWyJqk4Az04MH74',
    appId: '1:395797911887:web:8ff2ee2e141d6a416ccd3a',
    messagingSenderId: '395797911887',
    projectId: 'tetra-6c0ee',
    authDomain: 'tetra-6c0ee.firebaseapp.com',
    databaseURL: 'https://tetra-6c0ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tetra-6c0ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCey1oIH5f710N_lC8BA3EGtv3KyH1BTrg',
    appId: '1:395797911887:android:60d20a401fdd04c16ccd3a',
    messagingSenderId: '395797911887',
    projectId: 'tetra-6c0ee',
    databaseURL: 'https://tetra-6c0ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tetra-6c0ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJUnODMxCCwZPqX2XLyX8oisG7IBg4QJg',
    appId: '1:395797911887:ios:adac31b874ed06d56ccd3a',
    messagingSenderId: '395797911887',
    projectId: 'tetra-6c0ee',
    databaseURL: 'https://tetra-6c0ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tetra-6c0ee.appspot.com',
    iosClientId: '395797911887-sfimbi1bpa8strole6f755olcpa0jflh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tetra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJUnODMxCCwZPqX2XLyX8oisG7IBg4QJg',
    appId: '1:395797911887:ios:adac31b874ed06d56ccd3a',
    messagingSenderId: '395797911887',
    projectId: 'tetra-6c0ee',
    databaseURL: 'https://tetra-6c0ee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tetra-6c0ee.appspot.com',
    iosClientId: '395797911887-sfimbi1bpa8strole6f755olcpa0jflh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tetra',
  );
}
